version: "3"
services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=dalong"
  pgbouncer:
    image: brainsam/pgbouncer
    ports:
      - "6543:6543"
    volumes:
      - "./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini"
      - "./users.txt:/opt/auth/users.txt"
  app:
    image: kksudo/odyssey-docker:1.1
    ports:
      - "6432:6432"
    volumes:
      - "./odyssey-dev.conf:/etc/odyssey/odyssey.conf"
  prom1:
    image: jwitrick/pgbouncer_exporter:v0.4.1
    ports:
    - "9127:9127"
    command: --pgBouncer.connectionString="postgres://postgres:dalong@1pgbouncer:6543/pgbouncer?sslmode=disable"
  prom2:
    image: jwitrick/pgbouncer_exporter:v0.4.1
    ports:
    - "9128:9127"
    command: --pgBouncer.connectionString="postgres://postgres:dalong@app:6432/console?sslmode=disable"